### ISSUE TITLE
Pinout documentation

### ISSUE THREAD

**Issue by jhbruhn** [Jan--Henrik/ESP-TC-PROG#1]
I'm thinking about making my ESP-based Project(s) tag-connect compatible to ease programmability and for the obvious tag-connect-niceness-factor. For that I'm trying to figure out whether there's some more-or-less established pinout you used while making this adapter.

And even if there's no such de-facto standard, a diagram in the readme would be very useful to get a sense for the pinout this adapter uses :) I'm thinking about ordering one for myself because this looks very handy (and sleek!).

**Comment by Jana-Marie** [comment]
Added a KiCAD lib and some images, thank you for the input! :) https://github.com/Jana-Marie/ESP-TC-PROG/tree/main/KiCAD-libs
